version: "3.6"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "8080:8080"
      - "4569:4569"
      - "4574:4574"
    environment:
      - SERVICES=dynamodb,lambda
      - DEFAULT_REGION=ap-northeast-1
      - DOCKER_HOST=unix:///var/run/docker.sock